// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	FacebookID  string    `gorm:"column:facebook_id;primaryKey" json:"facebook_id"`
	LastName    string    `gorm:"column:last_name" json:"last_name"`
	Image       string    `gorm:"column:image" json:"image"`
	PhoneNumber int64     `gorm:"column:phone_number" json:"phone_number"`
	FirstName   string    `gorm:"column:first_name" json:"first_name"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	PageID      string    `gorm:"column:page_id;not null" json:"page_id"`
	Gender      int32     `gorm:"column:gender;not null" json:"gender"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
