// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDistrict = "districts"

// District mapped from table <districts>
type District struct {
	ID         int32  `gorm:"column:id;primaryKey" json:"id"`
	ProvinceID int32  `gorm:"column:province_id" json:"province_id"`
	DrName     string `gorm:"column:dr_name" json:"dr_name"`
	DrNameEn   string `gorm:"column:dr_name_en" json:"dr_name_en"`
}

// TableName District's table name
func (*District) TableName() string {
	return TableNameDistrict
}
