// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameExpense = "expenses"

// Expense mapped from table <expenses>
type Expense struct {
	ID          string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	ExpenseDate time.Time `gorm:"column:expense_date;not null" json:"expense_date"`
	Amount      float64   `gorm:"column:amount;not null" json:"amount"`
	Description string    `gorm:"column:description" json:"description"`
	ReceiptURL  string    `gorm:"column:receipt_url" json:"receipt_url"`
	ProductID   string    `gorm:"column:product_id" json:"product_id"`
	CategoryID  string    `gorm:"column:category_id;not null" json:"category_id"`
	SupplierID  string    `gorm:"column:supplier_id" json:"supplier_id"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Expense's table name
func (*Expense) TableName() string {
	return TableNameExpense
}
