// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameExpenseCategory = "expense_categories"

// ExpenseCategory mapped from table <expense_categories>
type ExpenseCategory struct {
	ID           string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	CategoryName string `gorm:"column:category_name;not null" json:"category_name"`
	Description  string `gorm:"column:description" json:"description"`
}

// TableName ExpenseCategory's table name
func (*ExpenseCategory) TableName() string {
	return TableNameExpenseCategory
}
