// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFacebookAdLead = "facebook_ad_leads"

// FacebookAdLead mapped from table <facebook_ad_leads>
type FacebookAdLead struct {
	UserID    string    `gorm:"column:user_id" json:"user_id"`
	AdID      string    `gorm:"column:ad_id;not null" json:"ad_id"`
	AdTitle   string    `gorm:"column:ad_title" json:"ad_title"`
	PageID    string    `gorm:"column:page_id" json:"page_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	ID        string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
}

// TableName FacebookAdLead's table name
func (*FacebookAdLead) TableName() string {
	return TableNameFacebookAdLead
}
