// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameImportProductsDatailItem = "import_products_datail_items"

// ImportProductsDatailItem mapped from table <import_products_datail_items>
type ImportProductsDatailItem struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	SizeID    string    `gorm:"column:size_id;not null" json:"size_id"`
	Quantity  int32     `gorm:"column:quantity;not null" json:"quantity"`
	Status    int64     `gorm:"column:status;not null" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName ImportProductsDatailItem's table name
func (*ImportProductsDatailItem) TableName() string {
	return TableNameImportProductsDatailItem
}
