// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameImportProductsDatail = "import_products_datails"

// ImportProductsDatail mapped from table <import_products_datails>
type ImportProductsDatail struct {
	ID              string  `gorm:"column:id;primaryKey" json:"id"`
	ImportProductID string  `gorm:"column:import_product_id;not null" json:"import_product_id"`
	ProductDetailID string  `gorm:"column:product_detail_id;not null" json:"product_detail_id"`
	Status          string  `gorm:"column:status;not null" json:"status"`
	Price           float64 `gorm:"column:price;not null" json:"price"`
}

// TableName ImportProductsDatail's table name
func (*ImportProductsDatail) TableName() string {
	return TableNameImportProductsDatail
}
