// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameImportProduct = "import_products"

// ImportProduct mapped from table <import_products>
type ImportProduct struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	ProductID         string    `gorm:"column:product_id;not null" json:"product_id"`
	TrackNo           string    `gorm:"column:track_no;not null" json:"track_no"`
	ImportDate        time.Time `gorm:"column:import_date;not null" json:"import_date"`
	SuccessImportDate time.Time `gorm:"column:success_import_date" json:"success_import_date"`
	UserID            string    `gorm:"column:user_id;not null" json:"user_id"`
	Description       string    `gorm:"column:description" json:"description"`
	Status            string    `gorm:"column:status;not null" json:"status"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName ImportProduct's table name
func (*ImportProduct) TableName() string {
	return TableNameImportProduct
}
