// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameIncomeCategory = "income_categories"

// IncomeCategory mapped from table <income_categories>
type IncomeCategory struct {
	ID           string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	CategoryName string `gorm:"column:category_name;not null" json:"category_name"`
	Description  string `gorm:"column:description" json:"description"`
}

// TableName IncomeCategory's table name
func (*IncomeCategory) TableName() string {
	return TableNameIncomeCategory
}
