// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameIncome = "incomes"

// Income mapped from table <incomes>
type Income struct {
	ID          string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	IncomeDate  time.Time `gorm:"column:income_date;not null" json:"income_date"`
	Amount      float64   `gorm:"column:amount;not null" json:"amount"`
	Description string    `gorm:"column:description" json:"description"`
	SlipURL     string    `gorm:"column:slip_url" json:"slip_url"`
	ProductID   string    `gorm:"column:product_id" json:"product_id"`
	CategoryID  string    `gorm:"column:category_id;not null" json:"category_id"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Income's table name
func (*Income) TableName() string {
	return TableNameIncome
}
