// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOrderStockDetail = "order_stock_details"

// OrderStockDetail mapped from table <order_stock_details>
type OrderStockDetail struct {
	ID                   string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	StockProductDetailID string `gorm:"column:stock_product_detail_id" json:"stock_product_detail_id"`
	OrderID              string `gorm:"column:order_id;not null" json:"order_id"`
	Quatity              int32  `gorm:"column:quatity;not null" json:"quatity"`
}

// TableName OrderStockDetail's table name
func (*OrderStockDetail) TableName() string {
	return TableNameOrderStockDetail
}
