// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameOrderDiscount = "order_discounts"

// OrderDiscount mapped from table <order_discounts>
type OrderDiscount struct {
	ID            string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	OrderID       string    `gorm:"column:order_id;not null" json:"order_id"`
	ProductID     string    `gorm:"column:product_id;not null" json:"product_id"`
	TotalDiscount float64   `gorm:"column:total_discount;not null" json:"total_discount"`
	DiscountID    string    `gorm:"column:discount_id;not null" json:"discount_id"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName OrderDiscount's table name
func (*OrderDiscount) TableName() string {
	return TableNameOrderDiscount
}
