// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameOrderProduct = "order_products"

// OrderProduct mapped from table <order_products>
type OrderProduct struct {
	ID                string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	OrderID           string    `gorm:"column:order_id;not null" json:"order_id"`
	Discount          float64   `gorm:"column:discount;not null" json:"discount"`
	ProductID         string    `gorm:"column:product_id" json:"product_id"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	TotalAmounts      int32     `gorm:"column:total_amounts;not null" json:"total_amounts"`
	TotalProductPrice float64   `gorm:"column:total_product_price;not null" json:"total_product_price"`
}

// TableName OrderProduct's table name
func (*OrderProduct) TableName() string {
	return TableNameOrderProduct
}
