// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameOrderDetail = "order_details"

// OrderDetail mapped from table <order_details>
type OrderDetail struct {
	OrderDetailID   string    `gorm:"column:order_detail_id;primaryKey;default:gen_random_uuid()" json:"order_detail_id"`
	OrderID         string    `gorm:"column:order_id;not null" json:"order_id"`
	ProductDetailID string    `gorm:"column:product_detail_id;not null" json:"product_detail_id"`
	Quantity        int32     `gorm:"column:quantity;not null" json:"quantity"`
	UnitPrice       float64   `gorm:"column:unit_price;not null" json:"unit_price"`
	TotalPrice      float64   `gorm:"column:total_price;not null" json:"total_price"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName OrderDetail's table name
func (*OrderDetail) TableName() string {
	return TableNameOrderDetail
}
