// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameOrderProductDiscount = "order_product_discounts"

// OrderProductDiscount mapped from table <order_product_discounts>
type OrderProductDiscount struct {
	ID               string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	OrderProductID   string    `gorm:"column:order_product_id;not null" json:"order_product_id"`
	PromotionPriceID string    `gorm:"column:promotion_price_id;not null" json:"promotion_price_id"`
	Discount         float64   `gorm:"column:discount;not null" json:"discount"`
	CreatedAt        time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdateAt         time.Time `gorm:"column:update_at;default:now()" json:"update_at"`
}

// TableName OrderProductDiscount's table name
func (*OrderProductDiscount) TableName() string {
	return TableNameOrderProductDiscount
}
