// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameProductDetail = "product_details"

// ProductDetail mapped from table <product_details>
type ProductDetail struct {
	ID        string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	ProductID string    `gorm:"column:product_id;not null" json:"product_id"`
	Color     string    `gorm:"column:color" json:"color"`
	FitType   string    `gorm:"column:fit_type" json:"fit_type"`
	Material  string    `gorm:"column:material" json:"material"`
	Status    string    `gorm:"column:status;default:active" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`
	ImageURL  string    `gorm:"column:image_url;default:N/A" json:"image_url"`
	ColorName string    `gorm:"column:color_name" json:"color_name"`
}

// TableName ProductDetail's table name
func (*ProductDetail) TableName() string {
	return TableNameProductDetail
}
