// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProductsResearch = "products_research"

// ProductsResearch mapped from table <products_research>
type ProductsResearch struct {
	ID                 float64 `gorm:"column:id ;primaryKey" json:"id "`
	Link               string  `gorm:"column:link" json:"link"`
	ProductsDetails    string  `gorm:"column:products_details" json:"products_details"`
	ProductsLaoDetails string  `gorm:"column:products_lao_details" json:"products_lao_details"`
}

// TableName ProductsResearch's table name
func (*ProductsResearch) TableName() string {
	return TableNameProductsResearch
}
