// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePromotion = "promotions"

// Promotion mapped from table <promotions>
type Promotion struct {
	ID        string  `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	ProductID string  `gorm:"column:product_id;not null" json:"product_id"`
	Discount  float32 `gorm:"column:discount;not null" json:"discount"`
	Status    string  `gorm:"column:status;not null;default:active" json:"status"`
	Quentity  int32   `gorm:"column:quentity;not null" json:"quentity"`
}

// TableName Promotion's table name
func (*Promotion) TableName() string {
	return TableNamePromotion
}
