// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameShipping = "shippings"

// Shipping mapped from table <shippings>
type Shipping struct {
	ID     string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name   string `gorm:"column:name" json:"name"`
	Status string `gorm:"column:status" json:"status"`
}

// TableName Shipping's table name
func (*Shipping) TableName() string {
	return TableNameShipping
}
