// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSize = "sizes"

// Size mapped from table <sizes>
type Size struct {
	ID              string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Size            string `gorm:"column:size" json:"size"`
	ProductDetailID string `gorm:"column:product_detail_id;not null" json:"product_detail_id"`
}

// TableName Size's table name
func (*Size) TableName() string {
	return TableNameSize
}
