// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStockDetail = "stock_details"

// StockDetail mapped from table <stock_details>
type StockDetail struct {
	ID                   string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	StockProductDetailID string `gorm:"column:stock_product_detail_id" json:"stock_product_detail_id"`
	OrderID              string `gorm:"column:order_id;not null" json:"order_id"`
}

// TableName StockDetail's table name
func (*StockDetail) TableName() string {
	return TableNameStockDetail
}
