// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStockProductDetail = "stock_product_details"

// StockProductDetail mapped from table <stock_product_details>
type StockProductDetail struct {
	ID              string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	ProductDetailID string    `gorm:"column:product_detail_id;not null" json:"product_detail_id"`
	Quantity        int32     `gorm:"column:quantity;not null" json:"quantity"`
	Status          string    `gorm:"column:status;default:active" json:"status"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`
	UserID          string    `gorm:"column:user_id;not null" json:"user_id"`
	Remaining       int32     `gorm:"column:remaining" json:"remaining"`
	SizeID          string    `gorm:"column:size_id;not null" json:"size_id"`
}

// TableName StockProductDetail's table name
func (*StockProductDetail) TableName() string {
	return TableNameStockProductDetail
}
