// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSupplier = "suppliers"

// Supplier mapped from table <suppliers>
type Supplier struct {
	ID            string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	SupplierName  string `gorm:"column:supplier_name;not null" json:"supplier_name"`
	ContactPerson string `gorm:"column:contact_person" json:"contact_person"`
	Email         string `gorm:"column:email" json:"email"`
	Phone         string `gorm:"column:phone" json:"phone"`
}

// TableName Supplier's table name
func (*Supplier) TableName() string {
	return TableNameSupplier
}
