// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUnit = "units"

// Unit mapped from table <units>
type Unit struct {
	ID       string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UnitName string `gorm:"column:unit_name;not null" json:"unit_name"`
	Status   string `gorm:"column:status;not null;default:active" json:"status"`
}

// TableName Unit's table name
func (*Unit) TableName() string {
	return TableNameUnit
}
