// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID       string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Password string `gorm:"column:password;not null" json:"password"`
	UserName string `gorm:"column:user_name;not null" json:"user_name"`
	Status   string `gorm:"column:status;not null;default:active" json:"status"`
	PageID   string `gorm:"column:page_id;not null" json:"page_id"`
	Rolo     string `gorm:"column:rolo;not null" json:"rolo"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
