// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
