// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameVillage = "villages"

// Village mapped from table <villages>
type Village struct {
	ID         int32  `gorm:"column:id;primaryKey" json:"id"`
	DistrictID int32  `gorm:"column:district_id" json:"district_id"`
	VillName   string `gorm:"column:vill_name" json:"vill_name"`
	VillNameEn string `gorm:"column:vill_name_en" json:"vill_name_en"`
}

// TableName Village's table name
func (*Village) TableName() string {
	return TableNameVillage
}
