// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormmodels

import (
	"time"
)

const TableNameChat = "chats"

// Chat mapped from table <chats>
type Chat struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SenderID    string    `gorm:"column:sender_id;not null" json:"sender_id"`
	RecipientID string    `gorm:"column:recipient_id;not null" json:"recipient_id"`
	Message     string    `gorm:"column:message;not null" json:"message"`
	CreatedAt   time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName Chat's table name
func (*Chat) TableName() string {
	return TableNameChat
}
