// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-api/internal/pkg/models"
)

func newExpenseCategory(db *gorm.DB, opts ...gen.DOOption) expenseCategory {
	_expenseCategory := expenseCategory{}

	_expenseCategory.expenseCategoryDo.UseDB(db, opts...)
	_expenseCategory.expenseCategoryDo.UseModel(&models.ExpenseCategory{})

	tableName := _expenseCategory.expenseCategoryDo.TableName()
	_expenseCategory.ALL = field.NewAsterisk(tableName)
	_expenseCategory.ID = field.NewString(tableName, "id")
	_expenseCategory.CategoryName = field.NewString(tableName, "category_name")
	_expenseCategory.Description = field.NewString(tableName, "description")

	_expenseCategory.fillFieldMap()

	return _expenseCategory
}

type expenseCategory struct {
	expenseCategoryDo

	ALL          field.Asterisk
	ID           field.String
	CategoryName field.String
	Description  field.String

	fieldMap map[string]field.Expr
}

func (e expenseCategory) Table(newTableName string) *expenseCategory {
	e.expenseCategoryDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e expenseCategory) As(alias string) *expenseCategory {
	e.expenseCategoryDo.DO = *(e.expenseCategoryDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *expenseCategory) updateTableName(table string) *expenseCategory {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewString(table, "id")
	e.CategoryName = field.NewString(table, "category_name")
	e.Description = field.NewString(table, "description")

	e.fillFieldMap()

	return e
}

func (e *expenseCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *expenseCategory) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 3)
	e.fieldMap["id"] = e.ID
	e.fieldMap["category_name"] = e.CategoryName
	e.fieldMap["description"] = e.Description
}

func (e expenseCategory) clone(db *gorm.DB) expenseCategory {
	e.expenseCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e expenseCategory) replaceDB(db *gorm.DB) expenseCategory {
	e.expenseCategoryDo.ReplaceDB(db)
	return e
}

type expenseCategoryDo struct{ gen.DO }

type IExpenseCategoryDo interface {
	gen.SubQuery
	Debug() IExpenseCategoryDo
	WithContext(ctx context.Context) IExpenseCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IExpenseCategoryDo
	WriteDB() IExpenseCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IExpenseCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IExpenseCategoryDo
	Not(conds ...gen.Condition) IExpenseCategoryDo
	Or(conds ...gen.Condition) IExpenseCategoryDo
	Select(conds ...field.Expr) IExpenseCategoryDo
	Where(conds ...gen.Condition) IExpenseCategoryDo
	Order(conds ...field.Expr) IExpenseCategoryDo
	Distinct(cols ...field.Expr) IExpenseCategoryDo
	Omit(cols ...field.Expr) IExpenseCategoryDo
	Join(table schema.Tabler, on ...field.Expr) IExpenseCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IExpenseCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IExpenseCategoryDo
	Group(cols ...field.Expr) IExpenseCategoryDo
	Having(conds ...gen.Condition) IExpenseCategoryDo
	Limit(limit int) IExpenseCategoryDo
	Offset(offset int) IExpenseCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IExpenseCategoryDo
	Unscoped() IExpenseCategoryDo
	Create(values ...*models.ExpenseCategory) error
	CreateInBatches(values []*models.ExpenseCategory, batchSize int) error
	Save(values ...*models.ExpenseCategory) error
	First() (*models.ExpenseCategory, error)
	Take() (*models.ExpenseCategory, error)
	Last() (*models.ExpenseCategory, error)
	Find() ([]*models.ExpenseCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ExpenseCategory, err error)
	FindInBatches(result *[]*models.ExpenseCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ExpenseCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IExpenseCategoryDo
	Assign(attrs ...field.AssignExpr) IExpenseCategoryDo
	Joins(fields ...field.RelationField) IExpenseCategoryDo
	Preload(fields ...field.RelationField) IExpenseCategoryDo
	FirstOrInit() (*models.ExpenseCategory, error)
	FirstOrCreate() (*models.ExpenseCategory, error)
	FindByPage(offset int, limit int) (result []*models.ExpenseCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IExpenseCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e expenseCategoryDo) Debug() IExpenseCategoryDo {
	return e.withDO(e.DO.Debug())
}

func (e expenseCategoryDo) WithContext(ctx context.Context) IExpenseCategoryDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e expenseCategoryDo) ReadDB() IExpenseCategoryDo {
	return e.Clauses(dbresolver.Read)
}

func (e expenseCategoryDo) WriteDB() IExpenseCategoryDo {
	return e.Clauses(dbresolver.Write)
}

func (e expenseCategoryDo) Session(config *gorm.Session) IExpenseCategoryDo {
	return e.withDO(e.DO.Session(config))
}

func (e expenseCategoryDo) Clauses(conds ...clause.Expression) IExpenseCategoryDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e expenseCategoryDo) Returning(value interface{}, columns ...string) IExpenseCategoryDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e expenseCategoryDo) Not(conds ...gen.Condition) IExpenseCategoryDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e expenseCategoryDo) Or(conds ...gen.Condition) IExpenseCategoryDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e expenseCategoryDo) Select(conds ...field.Expr) IExpenseCategoryDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e expenseCategoryDo) Where(conds ...gen.Condition) IExpenseCategoryDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e expenseCategoryDo) Order(conds ...field.Expr) IExpenseCategoryDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e expenseCategoryDo) Distinct(cols ...field.Expr) IExpenseCategoryDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e expenseCategoryDo) Omit(cols ...field.Expr) IExpenseCategoryDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e expenseCategoryDo) Join(table schema.Tabler, on ...field.Expr) IExpenseCategoryDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e expenseCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IExpenseCategoryDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e expenseCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IExpenseCategoryDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e expenseCategoryDo) Group(cols ...field.Expr) IExpenseCategoryDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e expenseCategoryDo) Having(conds ...gen.Condition) IExpenseCategoryDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e expenseCategoryDo) Limit(limit int) IExpenseCategoryDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e expenseCategoryDo) Offset(offset int) IExpenseCategoryDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e expenseCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IExpenseCategoryDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e expenseCategoryDo) Unscoped() IExpenseCategoryDo {
	return e.withDO(e.DO.Unscoped())
}

func (e expenseCategoryDo) Create(values ...*models.ExpenseCategory) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e expenseCategoryDo) CreateInBatches(values []*models.ExpenseCategory, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e expenseCategoryDo) Save(values ...*models.ExpenseCategory) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e expenseCategoryDo) First() (*models.ExpenseCategory, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ExpenseCategory), nil
	}
}

func (e expenseCategoryDo) Take() (*models.ExpenseCategory, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ExpenseCategory), nil
	}
}

func (e expenseCategoryDo) Last() (*models.ExpenseCategory, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ExpenseCategory), nil
	}
}

func (e expenseCategoryDo) Find() ([]*models.ExpenseCategory, error) {
	result, err := e.DO.Find()
	return result.([]*models.ExpenseCategory), err
}

func (e expenseCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ExpenseCategory, err error) {
	buf := make([]*models.ExpenseCategory, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e expenseCategoryDo) FindInBatches(result *[]*models.ExpenseCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e expenseCategoryDo) Attrs(attrs ...field.AssignExpr) IExpenseCategoryDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e expenseCategoryDo) Assign(attrs ...field.AssignExpr) IExpenseCategoryDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e expenseCategoryDo) Joins(fields ...field.RelationField) IExpenseCategoryDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e expenseCategoryDo) Preload(fields ...field.RelationField) IExpenseCategoryDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e expenseCategoryDo) FirstOrInit() (*models.ExpenseCategory, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ExpenseCategory), nil
	}
}

func (e expenseCategoryDo) FirstOrCreate() (*models.ExpenseCategory, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ExpenseCategory), nil
	}
}

func (e expenseCategoryDo) FindByPage(offset int, limit int) (result []*models.ExpenseCategory, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e expenseCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e expenseCategoryDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e expenseCategoryDo) Delete(models ...*models.ExpenseCategory) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *expenseCategoryDo) withDO(do gen.Dao) *expenseCategoryDo {
	e.DO = *do.(*gen.DO)
	return e
}
