// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-api/internal/pkg/models"
)

func newFacebookAdLead(db *gorm.DB, opts ...gen.DOOption) facebookAdLead {
	_facebookAdLead := facebookAdLead{}

	_facebookAdLead.facebookAdLeadDo.UseDB(db, opts...)
	_facebookAdLead.facebookAdLeadDo.UseModel(&models.FacebookAdLead{})

	tableName := _facebookAdLead.facebookAdLeadDo.TableName()
	_facebookAdLead.ALL = field.NewAsterisk(tableName)
	_facebookAdLead.UserID = field.NewString(tableName, "user_id")
	_facebookAdLead.AdID = field.NewString(tableName, "ad_id")
	_facebookAdLead.AdTitle = field.NewString(tableName, "ad_title")
	_facebookAdLead.PageID = field.NewString(tableName, "page_id")
	_facebookAdLead.CreatedAt = field.NewTime(tableName, "created_at")
	_facebookAdLead.ID = field.NewString(tableName, "id")

	_facebookAdLead.fillFieldMap()

	return _facebookAdLead
}

type facebookAdLead struct {
	facebookAdLeadDo

	ALL       field.Asterisk
	UserID    field.String
	AdID      field.String
	AdTitle   field.String
	PageID    field.String
	CreatedAt field.Time
	ID        field.String

	fieldMap map[string]field.Expr
}

func (f facebookAdLead) Table(newTableName string) *facebookAdLead {
	f.facebookAdLeadDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f facebookAdLead) As(alias string) *facebookAdLead {
	f.facebookAdLeadDo.DO = *(f.facebookAdLeadDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *facebookAdLead) updateTableName(table string) *facebookAdLead {
	f.ALL = field.NewAsterisk(table)
	f.UserID = field.NewString(table, "user_id")
	f.AdID = field.NewString(table, "ad_id")
	f.AdTitle = field.NewString(table, "ad_title")
	f.PageID = field.NewString(table, "page_id")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.ID = field.NewString(table, "id")

	f.fillFieldMap()

	return f
}

func (f *facebookAdLead) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *facebookAdLead) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 6)
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["ad_id"] = f.AdID
	f.fieldMap["ad_title"] = f.AdTitle
	f.fieldMap["page_id"] = f.PageID
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["id"] = f.ID
}

func (f facebookAdLead) clone(db *gorm.DB) facebookAdLead {
	f.facebookAdLeadDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f facebookAdLead) replaceDB(db *gorm.DB) facebookAdLead {
	f.facebookAdLeadDo.ReplaceDB(db)
	return f
}

type facebookAdLeadDo struct{ gen.DO }

type IFacebookAdLeadDo interface {
	gen.SubQuery
	Debug() IFacebookAdLeadDo
	WithContext(ctx context.Context) IFacebookAdLeadDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFacebookAdLeadDo
	WriteDB() IFacebookAdLeadDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFacebookAdLeadDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFacebookAdLeadDo
	Not(conds ...gen.Condition) IFacebookAdLeadDo
	Or(conds ...gen.Condition) IFacebookAdLeadDo
	Select(conds ...field.Expr) IFacebookAdLeadDo
	Where(conds ...gen.Condition) IFacebookAdLeadDo
	Order(conds ...field.Expr) IFacebookAdLeadDo
	Distinct(cols ...field.Expr) IFacebookAdLeadDo
	Omit(cols ...field.Expr) IFacebookAdLeadDo
	Join(table schema.Tabler, on ...field.Expr) IFacebookAdLeadDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFacebookAdLeadDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFacebookAdLeadDo
	Group(cols ...field.Expr) IFacebookAdLeadDo
	Having(conds ...gen.Condition) IFacebookAdLeadDo
	Limit(limit int) IFacebookAdLeadDo
	Offset(offset int) IFacebookAdLeadDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFacebookAdLeadDo
	Unscoped() IFacebookAdLeadDo
	Create(values ...*models.FacebookAdLead) error
	CreateInBatches(values []*models.FacebookAdLead, batchSize int) error
	Save(values ...*models.FacebookAdLead) error
	First() (*models.FacebookAdLead, error)
	Take() (*models.FacebookAdLead, error)
	Last() (*models.FacebookAdLead, error)
	Find() ([]*models.FacebookAdLead, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FacebookAdLead, err error)
	FindInBatches(result *[]*models.FacebookAdLead, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.FacebookAdLead) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFacebookAdLeadDo
	Assign(attrs ...field.AssignExpr) IFacebookAdLeadDo
	Joins(fields ...field.RelationField) IFacebookAdLeadDo
	Preload(fields ...field.RelationField) IFacebookAdLeadDo
	FirstOrInit() (*models.FacebookAdLead, error)
	FirstOrCreate() (*models.FacebookAdLead, error)
	FindByPage(offset int, limit int) (result []*models.FacebookAdLead, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFacebookAdLeadDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f facebookAdLeadDo) Debug() IFacebookAdLeadDo {
	return f.withDO(f.DO.Debug())
}

func (f facebookAdLeadDo) WithContext(ctx context.Context) IFacebookAdLeadDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f facebookAdLeadDo) ReadDB() IFacebookAdLeadDo {
	return f.Clauses(dbresolver.Read)
}

func (f facebookAdLeadDo) WriteDB() IFacebookAdLeadDo {
	return f.Clauses(dbresolver.Write)
}

func (f facebookAdLeadDo) Session(config *gorm.Session) IFacebookAdLeadDo {
	return f.withDO(f.DO.Session(config))
}

func (f facebookAdLeadDo) Clauses(conds ...clause.Expression) IFacebookAdLeadDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f facebookAdLeadDo) Returning(value interface{}, columns ...string) IFacebookAdLeadDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f facebookAdLeadDo) Not(conds ...gen.Condition) IFacebookAdLeadDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f facebookAdLeadDo) Or(conds ...gen.Condition) IFacebookAdLeadDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f facebookAdLeadDo) Select(conds ...field.Expr) IFacebookAdLeadDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f facebookAdLeadDo) Where(conds ...gen.Condition) IFacebookAdLeadDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f facebookAdLeadDo) Order(conds ...field.Expr) IFacebookAdLeadDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f facebookAdLeadDo) Distinct(cols ...field.Expr) IFacebookAdLeadDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f facebookAdLeadDo) Omit(cols ...field.Expr) IFacebookAdLeadDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f facebookAdLeadDo) Join(table schema.Tabler, on ...field.Expr) IFacebookAdLeadDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f facebookAdLeadDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFacebookAdLeadDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f facebookAdLeadDo) RightJoin(table schema.Tabler, on ...field.Expr) IFacebookAdLeadDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f facebookAdLeadDo) Group(cols ...field.Expr) IFacebookAdLeadDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f facebookAdLeadDo) Having(conds ...gen.Condition) IFacebookAdLeadDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f facebookAdLeadDo) Limit(limit int) IFacebookAdLeadDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f facebookAdLeadDo) Offset(offset int) IFacebookAdLeadDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f facebookAdLeadDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFacebookAdLeadDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f facebookAdLeadDo) Unscoped() IFacebookAdLeadDo {
	return f.withDO(f.DO.Unscoped())
}

func (f facebookAdLeadDo) Create(values ...*models.FacebookAdLead) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f facebookAdLeadDo) CreateInBatches(values []*models.FacebookAdLead, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f facebookAdLeadDo) Save(values ...*models.FacebookAdLead) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f facebookAdLeadDo) First() (*models.FacebookAdLead, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.FacebookAdLead), nil
	}
}

func (f facebookAdLeadDo) Take() (*models.FacebookAdLead, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.FacebookAdLead), nil
	}
}

func (f facebookAdLeadDo) Last() (*models.FacebookAdLead, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.FacebookAdLead), nil
	}
}

func (f facebookAdLeadDo) Find() ([]*models.FacebookAdLead, error) {
	result, err := f.DO.Find()
	return result.([]*models.FacebookAdLead), err
}

func (f facebookAdLeadDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FacebookAdLead, err error) {
	buf := make([]*models.FacebookAdLead, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f facebookAdLeadDo) FindInBatches(result *[]*models.FacebookAdLead, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f facebookAdLeadDo) Attrs(attrs ...field.AssignExpr) IFacebookAdLeadDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f facebookAdLeadDo) Assign(attrs ...field.AssignExpr) IFacebookAdLeadDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f facebookAdLeadDo) Joins(fields ...field.RelationField) IFacebookAdLeadDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f facebookAdLeadDo) Preload(fields ...field.RelationField) IFacebookAdLeadDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f facebookAdLeadDo) FirstOrInit() (*models.FacebookAdLead, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.FacebookAdLead), nil
	}
}

func (f facebookAdLeadDo) FirstOrCreate() (*models.FacebookAdLead, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.FacebookAdLead), nil
	}
}

func (f facebookAdLeadDo) FindByPage(offset int, limit int) (result []*models.FacebookAdLead, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f facebookAdLeadDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f facebookAdLeadDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f facebookAdLeadDo) Delete(models ...*models.FacebookAdLead) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *facebookAdLeadDo) withDO(do gen.Dao) *facebookAdLeadDo {
	f.DO = *do.(*gen.DO)
	return f
}
