// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-api/internal/pkg/models"
)

func newImportProductsDatailItem(db *gorm.DB, opts ...gen.DOOption) importProductsDatailItem {
	_importProductsDatailItem := importProductsDatailItem{}

	_importProductsDatailItem.importProductsDatailItemDo.UseDB(db, opts...)
	_importProductsDatailItem.importProductsDatailItemDo.UseModel(&models.ImportProductsDatailItem{})

	tableName := _importProductsDatailItem.importProductsDatailItemDo.TableName()
	_importProductsDatailItem.ALL = field.NewAsterisk(tableName)
	_importProductsDatailItem.ID = field.NewString(tableName, "id")
	_importProductsDatailItem.SizeID = field.NewString(tableName, "size_id")
	_importProductsDatailItem.Quantity = field.NewInt32(tableName, "quantity")
	_importProductsDatailItem.Status = field.NewInt64(tableName, "status")
	_importProductsDatailItem.CreatedAt = field.NewTime(tableName, "created_at")
	_importProductsDatailItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_importProductsDatailItem.fillFieldMap()

	return _importProductsDatailItem
}

type importProductsDatailItem struct {
	importProductsDatailItemDo

	ALL       field.Asterisk
	ID        field.String
	SizeID    field.String
	Quantity  field.Int32
	Status    field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (i importProductsDatailItem) Table(newTableName string) *importProductsDatailItem {
	i.importProductsDatailItemDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i importProductsDatailItem) As(alias string) *importProductsDatailItem {
	i.importProductsDatailItemDo.DO = *(i.importProductsDatailItemDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *importProductsDatailItem) updateTableName(table string) *importProductsDatailItem {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.SizeID = field.NewString(table, "size_id")
	i.Quantity = field.NewInt32(table, "quantity")
	i.Status = field.NewInt64(table, "status")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *importProductsDatailItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *importProductsDatailItem) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 6)
	i.fieldMap["id"] = i.ID
	i.fieldMap["size_id"] = i.SizeID
	i.fieldMap["quantity"] = i.Quantity
	i.fieldMap["status"] = i.Status
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i importProductsDatailItem) clone(db *gorm.DB) importProductsDatailItem {
	i.importProductsDatailItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i importProductsDatailItem) replaceDB(db *gorm.DB) importProductsDatailItem {
	i.importProductsDatailItemDo.ReplaceDB(db)
	return i
}

type importProductsDatailItemDo struct{ gen.DO }

type IImportProductsDatailItemDo interface {
	gen.SubQuery
	Debug() IImportProductsDatailItemDo
	WithContext(ctx context.Context) IImportProductsDatailItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IImportProductsDatailItemDo
	WriteDB() IImportProductsDatailItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IImportProductsDatailItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IImportProductsDatailItemDo
	Not(conds ...gen.Condition) IImportProductsDatailItemDo
	Or(conds ...gen.Condition) IImportProductsDatailItemDo
	Select(conds ...field.Expr) IImportProductsDatailItemDo
	Where(conds ...gen.Condition) IImportProductsDatailItemDo
	Order(conds ...field.Expr) IImportProductsDatailItemDo
	Distinct(cols ...field.Expr) IImportProductsDatailItemDo
	Omit(cols ...field.Expr) IImportProductsDatailItemDo
	Join(table schema.Tabler, on ...field.Expr) IImportProductsDatailItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IImportProductsDatailItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IImportProductsDatailItemDo
	Group(cols ...field.Expr) IImportProductsDatailItemDo
	Having(conds ...gen.Condition) IImportProductsDatailItemDo
	Limit(limit int) IImportProductsDatailItemDo
	Offset(offset int) IImportProductsDatailItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IImportProductsDatailItemDo
	Unscoped() IImportProductsDatailItemDo
	Create(values ...*models.ImportProductsDatailItem) error
	CreateInBatches(values []*models.ImportProductsDatailItem, batchSize int) error
	Save(values ...*models.ImportProductsDatailItem) error
	First() (*models.ImportProductsDatailItem, error)
	Take() (*models.ImportProductsDatailItem, error)
	Last() (*models.ImportProductsDatailItem, error)
	Find() ([]*models.ImportProductsDatailItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ImportProductsDatailItem, err error)
	FindInBatches(result *[]*models.ImportProductsDatailItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ImportProductsDatailItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IImportProductsDatailItemDo
	Assign(attrs ...field.AssignExpr) IImportProductsDatailItemDo
	Joins(fields ...field.RelationField) IImportProductsDatailItemDo
	Preload(fields ...field.RelationField) IImportProductsDatailItemDo
	FirstOrInit() (*models.ImportProductsDatailItem, error)
	FirstOrCreate() (*models.ImportProductsDatailItem, error)
	FindByPage(offset int, limit int) (result []*models.ImportProductsDatailItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IImportProductsDatailItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i importProductsDatailItemDo) Debug() IImportProductsDatailItemDo {
	return i.withDO(i.DO.Debug())
}

func (i importProductsDatailItemDo) WithContext(ctx context.Context) IImportProductsDatailItemDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i importProductsDatailItemDo) ReadDB() IImportProductsDatailItemDo {
	return i.Clauses(dbresolver.Read)
}

func (i importProductsDatailItemDo) WriteDB() IImportProductsDatailItemDo {
	return i.Clauses(dbresolver.Write)
}

func (i importProductsDatailItemDo) Session(config *gorm.Session) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Session(config))
}

func (i importProductsDatailItemDo) Clauses(conds ...clause.Expression) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i importProductsDatailItemDo) Returning(value interface{}, columns ...string) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i importProductsDatailItemDo) Not(conds ...gen.Condition) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i importProductsDatailItemDo) Or(conds ...gen.Condition) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i importProductsDatailItemDo) Select(conds ...field.Expr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i importProductsDatailItemDo) Where(conds ...gen.Condition) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i importProductsDatailItemDo) Order(conds ...field.Expr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i importProductsDatailItemDo) Distinct(cols ...field.Expr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i importProductsDatailItemDo) Omit(cols ...field.Expr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i importProductsDatailItemDo) Join(table schema.Tabler, on ...field.Expr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i importProductsDatailItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i importProductsDatailItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i importProductsDatailItemDo) Group(cols ...field.Expr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i importProductsDatailItemDo) Having(conds ...gen.Condition) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i importProductsDatailItemDo) Limit(limit int) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i importProductsDatailItemDo) Offset(offset int) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i importProductsDatailItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i importProductsDatailItemDo) Unscoped() IImportProductsDatailItemDo {
	return i.withDO(i.DO.Unscoped())
}

func (i importProductsDatailItemDo) Create(values ...*models.ImportProductsDatailItem) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i importProductsDatailItemDo) CreateInBatches(values []*models.ImportProductsDatailItem, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i importProductsDatailItemDo) Save(values ...*models.ImportProductsDatailItem) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i importProductsDatailItemDo) First() (*models.ImportProductsDatailItem, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatailItem), nil
	}
}

func (i importProductsDatailItemDo) Take() (*models.ImportProductsDatailItem, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatailItem), nil
	}
}

func (i importProductsDatailItemDo) Last() (*models.ImportProductsDatailItem, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatailItem), nil
	}
}

func (i importProductsDatailItemDo) Find() ([]*models.ImportProductsDatailItem, error) {
	result, err := i.DO.Find()
	return result.([]*models.ImportProductsDatailItem), err
}

func (i importProductsDatailItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ImportProductsDatailItem, err error) {
	buf := make([]*models.ImportProductsDatailItem, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i importProductsDatailItemDo) FindInBatches(result *[]*models.ImportProductsDatailItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i importProductsDatailItemDo) Attrs(attrs ...field.AssignExpr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i importProductsDatailItemDo) Assign(attrs ...field.AssignExpr) IImportProductsDatailItemDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i importProductsDatailItemDo) Joins(fields ...field.RelationField) IImportProductsDatailItemDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i importProductsDatailItemDo) Preload(fields ...field.RelationField) IImportProductsDatailItemDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i importProductsDatailItemDo) FirstOrInit() (*models.ImportProductsDatailItem, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatailItem), nil
	}
}

func (i importProductsDatailItemDo) FirstOrCreate() (*models.ImportProductsDatailItem, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatailItem), nil
	}
}

func (i importProductsDatailItemDo) FindByPage(offset int, limit int) (result []*models.ImportProductsDatailItem, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i importProductsDatailItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i importProductsDatailItemDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i importProductsDatailItemDo) Delete(models ...*models.ImportProductsDatailItem) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *importProductsDatailItemDo) withDO(do gen.Dao) *importProductsDatailItemDo {
	i.DO = *do.(*gen.DO)
	return i
}
