// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-api/internal/pkg/models"
)

func newImportProduct(db *gorm.DB, opts ...gen.DOOption) importProduct {
	_importProduct := importProduct{}

	_importProduct.importProductDo.UseDB(db, opts...)
	_importProduct.importProductDo.UseModel(&models.ImportProduct{})

	tableName := _importProduct.importProductDo.TableName()
	_importProduct.ALL = field.NewAsterisk(tableName)
	_importProduct.ID = field.NewString(tableName, "id")
	_importProduct.ProductID = field.NewString(tableName, "product_id")
	_importProduct.TrackNo = field.NewString(tableName, "track_no")
	_importProduct.ImportDate = field.NewTime(tableName, "import_date")
	_importProduct.SuccessImportDate = field.NewTime(tableName, "success_import_date")
	_importProduct.UserID = field.NewString(tableName, "user_id")
	_importProduct.Description = field.NewString(tableName, "description")
	_importProduct.Status = field.NewString(tableName, "status")
	_importProduct.CreatedAt = field.NewTime(tableName, "created_at")
	_importProduct.UpdatedAt = field.NewTime(tableName, "updated_at")

	_importProduct.fillFieldMap()

	return _importProduct
}

type importProduct struct {
	importProductDo

	ALL               field.Asterisk
	ID                field.String
	ProductID         field.String
	TrackNo           field.String
	ImportDate        field.Time
	SuccessImportDate field.Time
	UserID            field.String
	Description       field.String
	Status            field.String
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (i importProduct) Table(newTableName string) *importProduct {
	i.importProductDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i importProduct) As(alias string) *importProduct {
	i.importProductDo.DO = *(i.importProductDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *importProduct) updateTableName(table string) *importProduct {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.ProductID = field.NewString(table, "product_id")
	i.TrackNo = field.NewString(table, "track_no")
	i.ImportDate = field.NewTime(table, "import_date")
	i.SuccessImportDate = field.NewTime(table, "success_import_date")
	i.UserID = field.NewString(table, "user_id")
	i.Description = field.NewString(table, "description")
	i.Status = field.NewString(table, "status")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *importProduct) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *importProduct) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 10)
	i.fieldMap["id"] = i.ID
	i.fieldMap["product_id"] = i.ProductID
	i.fieldMap["track_no"] = i.TrackNo
	i.fieldMap["import_date"] = i.ImportDate
	i.fieldMap["success_import_date"] = i.SuccessImportDate
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["description"] = i.Description
	i.fieldMap["status"] = i.Status
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i importProduct) clone(db *gorm.DB) importProduct {
	i.importProductDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i importProduct) replaceDB(db *gorm.DB) importProduct {
	i.importProductDo.ReplaceDB(db)
	return i
}

type importProductDo struct{ gen.DO }

type IImportProductDo interface {
	gen.SubQuery
	Debug() IImportProductDo
	WithContext(ctx context.Context) IImportProductDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IImportProductDo
	WriteDB() IImportProductDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IImportProductDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IImportProductDo
	Not(conds ...gen.Condition) IImportProductDo
	Or(conds ...gen.Condition) IImportProductDo
	Select(conds ...field.Expr) IImportProductDo
	Where(conds ...gen.Condition) IImportProductDo
	Order(conds ...field.Expr) IImportProductDo
	Distinct(cols ...field.Expr) IImportProductDo
	Omit(cols ...field.Expr) IImportProductDo
	Join(table schema.Tabler, on ...field.Expr) IImportProductDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IImportProductDo
	RightJoin(table schema.Tabler, on ...field.Expr) IImportProductDo
	Group(cols ...field.Expr) IImportProductDo
	Having(conds ...gen.Condition) IImportProductDo
	Limit(limit int) IImportProductDo
	Offset(offset int) IImportProductDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IImportProductDo
	Unscoped() IImportProductDo
	Create(values ...*models.ImportProduct) error
	CreateInBatches(values []*models.ImportProduct, batchSize int) error
	Save(values ...*models.ImportProduct) error
	First() (*models.ImportProduct, error)
	Take() (*models.ImportProduct, error)
	Last() (*models.ImportProduct, error)
	Find() ([]*models.ImportProduct, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ImportProduct, err error)
	FindInBatches(result *[]*models.ImportProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ImportProduct) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IImportProductDo
	Assign(attrs ...field.AssignExpr) IImportProductDo
	Joins(fields ...field.RelationField) IImportProductDo
	Preload(fields ...field.RelationField) IImportProductDo
	FirstOrInit() (*models.ImportProduct, error)
	FirstOrCreate() (*models.ImportProduct, error)
	FindByPage(offset int, limit int) (result []*models.ImportProduct, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IImportProductDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i importProductDo) Debug() IImportProductDo {
	return i.withDO(i.DO.Debug())
}

func (i importProductDo) WithContext(ctx context.Context) IImportProductDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i importProductDo) ReadDB() IImportProductDo {
	return i.Clauses(dbresolver.Read)
}

func (i importProductDo) WriteDB() IImportProductDo {
	return i.Clauses(dbresolver.Write)
}

func (i importProductDo) Session(config *gorm.Session) IImportProductDo {
	return i.withDO(i.DO.Session(config))
}

func (i importProductDo) Clauses(conds ...clause.Expression) IImportProductDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i importProductDo) Returning(value interface{}, columns ...string) IImportProductDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i importProductDo) Not(conds ...gen.Condition) IImportProductDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i importProductDo) Or(conds ...gen.Condition) IImportProductDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i importProductDo) Select(conds ...field.Expr) IImportProductDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i importProductDo) Where(conds ...gen.Condition) IImportProductDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i importProductDo) Order(conds ...field.Expr) IImportProductDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i importProductDo) Distinct(cols ...field.Expr) IImportProductDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i importProductDo) Omit(cols ...field.Expr) IImportProductDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i importProductDo) Join(table schema.Tabler, on ...field.Expr) IImportProductDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i importProductDo) LeftJoin(table schema.Tabler, on ...field.Expr) IImportProductDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i importProductDo) RightJoin(table schema.Tabler, on ...field.Expr) IImportProductDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i importProductDo) Group(cols ...field.Expr) IImportProductDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i importProductDo) Having(conds ...gen.Condition) IImportProductDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i importProductDo) Limit(limit int) IImportProductDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i importProductDo) Offset(offset int) IImportProductDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i importProductDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IImportProductDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i importProductDo) Unscoped() IImportProductDo {
	return i.withDO(i.DO.Unscoped())
}

func (i importProductDo) Create(values ...*models.ImportProduct) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i importProductDo) CreateInBatches(values []*models.ImportProduct, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i importProductDo) Save(values ...*models.ImportProduct) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i importProductDo) First() (*models.ImportProduct, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProduct), nil
	}
}

func (i importProductDo) Take() (*models.ImportProduct, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProduct), nil
	}
}

func (i importProductDo) Last() (*models.ImportProduct, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProduct), nil
	}
}

func (i importProductDo) Find() ([]*models.ImportProduct, error) {
	result, err := i.DO.Find()
	return result.([]*models.ImportProduct), err
}

func (i importProductDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ImportProduct, err error) {
	buf := make([]*models.ImportProduct, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i importProductDo) FindInBatches(result *[]*models.ImportProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i importProductDo) Attrs(attrs ...field.AssignExpr) IImportProductDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i importProductDo) Assign(attrs ...field.AssignExpr) IImportProductDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i importProductDo) Joins(fields ...field.RelationField) IImportProductDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i importProductDo) Preload(fields ...field.RelationField) IImportProductDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i importProductDo) FirstOrInit() (*models.ImportProduct, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProduct), nil
	}
}

func (i importProductDo) FirstOrCreate() (*models.ImportProduct, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProduct), nil
	}
}

func (i importProductDo) FindByPage(offset int, limit int) (result []*models.ImportProduct, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i importProductDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i importProductDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i importProductDo) Delete(models ...*models.ImportProduct) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *importProductDo) withDO(do gen.Dao) *importProductDo {
	i.DO = *do.(*gen.DO)
	return i
}
