// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-api/internal/pkg/models"
)

func newImportProductsDatail(db *gorm.DB, opts ...gen.DOOption) importProductsDatail {
	_importProductsDatail := importProductsDatail{}

	_importProductsDatail.importProductsDatailDo.UseDB(db, opts...)
	_importProductsDatail.importProductsDatailDo.UseModel(&models.ImportProductsDatail{})

	tableName := _importProductsDatail.importProductsDatailDo.TableName()
	_importProductsDatail.ALL = field.NewAsterisk(tableName)
	_importProductsDatail.ID = field.NewString(tableName, "id")
	_importProductsDatail.ImportProductID = field.NewString(tableName, "import_product_id")
	_importProductsDatail.ProductDetailID = field.NewString(tableName, "product_detail_id")
	_importProductsDatail.Status = field.NewString(tableName, "status")
	_importProductsDatail.Price = field.NewFloat64(tableName, "price")

	_importProductsDatail.fillFieldMap()

	return _importProductsDatail
}

type importProductsDatail struct {
	importProductsDatailDo

	ALL             field.Asterisk
	ID              field.String
	ImportProductID field.String
	ProductDetailID field.String
	Status          field.String
	Price           field.Float64

	fieldMap map[string]field.Expr
}

func (i importProductsDatail) Table(newTableName string) *importProductsDatail {
	i.importProductsDatailDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i importProductsDatail) As(alias string) *importProductsDatail {
	i.importProductsDatailDo.DO = *(i.importProductsDatailDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *importProductsDatail) updateTableName(table string) *importProductsDatail {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.ImportProductID = field.NewString(table, "import_product_id")
	i.ProductDetailID = field.NewString(table, "product_detail_id")
	i.Status = field.NewString(table, "status")
	i.Price = field.NewFloat64(table, "price")

	i.fillFieldMap()

	return i
}

func (i *importProductsDatail) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *importProductsDatail) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 5)
	i.fieldMap["id"] = i.ID
	i.fieldMap["import_product_id"] = i.ImportProductID
	i.fieldMap["product_detail_id"] = i.ProductDetailID
	i.fieldMap["status"] = i.Status
	i.fieldMap["price"] = i.Price
}

func (i importProductsDatail) clone(db *gorm.DB) importProductsDatail {
	i.importProductsDatailDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i importProductsDatail) replaceDB(db *gorm.DB) importProductsDatail {
	i.importProductsDatailDo.ReplaceDB(db)
	return i
}

type importProductsDatailDo struct{ gen.DO }

type IImportProductsDatailDo interface {
	gen.SubQuery
	Debug() IImportProductsDatailDo
	WithContext(ctx context.Context) IImportProductsDatailDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IImportProductsDatailDo
	WriteDB() IImportProductsDatailDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IImportProductsDatailDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IImportProductsDatailDo
	Not(conds ...gen.Condition) IImportProductsDatailDo
	Or(conds ...gen.Condition) IImportProductsDatailDo
	Select(conds ...field.Expr) IImportProductsDatailDo
	Where(conds ...gen.Condition) IImportProductsDatailDo
	Order(conds ...field.Expr) IImportProductsDatailDo
	Distinct(cols ...field.Expr) IImportProductsDatailDo
	Omit(cols ...field.Expr) IImportProductsDatailDo
	Join(table schema.Tabler, on ...field.Expr) IImportProductsDatailDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IImportProductsDatailDo
	RightJoin(table schema.Tabler, on ...field.Expr) IImportProductsDatailDo
	Group(cols ...field.Expr) IImportProductsDatailDo
	Having(conds ...gen.Condition) IImportProductsDatailDo
	Limit(limit int) IImportProductsDatailDo
	Offset(offset int) IImportProductsDatailDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IImportProductsDatailDo
	Unscoped() IImportProductsDatailDo
	Create(values ...*models.ImportProductsDatail) error
	CreateInBatches(values []*models.ImportProductsDatail, batchSize int) error
	Save(values ...*models.ImportProductsDatail) error
	First() (*models.ImportProductsDatail, error)
	Take() (*models.ImportProductsDatail, error)
	Last() (*models.ImportProductsDatail, error)
	Find() ([]*models.ImportProductsDatail, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ImportProductsDatail, err error)
	FindInBatches(result *[]*models.ImportProductsDatail, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ImportProductsDatail) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IImportProductsDatailDo
	Assign(attrs ...field.AssignExpr) IImportProductsDatailDo
	Joins(fields ...field.RelationField) IImportProductsDatailDo
	Preload(fields ...field.RelationField) IImportProductsDatailDo
	FirstOrInit() (*models.ImportProductsDatail, error)
	FirstOrCreate() (*models.ImportProductsDatail, error)
	FindByPage(offset int, limit int) (result []*models.ImportProductsDatail, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IImportProductsDatailDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i importProductsDatailDo) Debug() IImportProductsDatailDo {
	return i.withDO(i.DO.Debug())
}

func (i importProductsDatailDo) WithContext(ctx context.Context) IImportProductsDatailDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i importProductsDatailDo) ReadDB() IImportProductsDatailDo {
	return i.Clauses(dbresolver.Read)
}

func (i importProductsDatailDo) WriteDB() IImportProductsDatailDo {
	return i.Clauses(dbresolver.Write)
}

func (i importProductsDatailDo) Session(config *gorm.Session) IImportProductsDatailDo {
	return i.withDO(i.DO.Session(config))
}

func (i importProductsDatailDo) Clauses(conds ...clause.Expression) IImportProductsDatailDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i importProductsDatailDo) Returning(value interface{}, columns ...string) IImportProductsDatailDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i importProductsDatailDo) Not(conds ...gen.Condition) IImportProductsDatailDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i importProductsDatailDo) Or(conds ...gen.Condition) IImportProductsDatailDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i importProductsDatailDo) Select(conds ...field.Expr) IImportProductsDatailDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i importProductsDatailDo) Where(conds ...gen.Condition) IImportProductsDatailDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i importProductsDatailDo) Order(conds ...field.Expr) IImportProductsDatailDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i importProductsDatailDo) Distinct(cols ...field.Expr) IImportProductsDatailDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i importProductsDatailDo) Omit(cols ...field.Expr) IImportProductsDatailDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i importProductsDatailDo) Join(table schema.Tabler, on ...field.Expr) IImportProductsDatailDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i importProductsDatailDo) LeftJoin(table schema.Tabler, on ...field.Expr) IImportProductsDatailDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i importProductsDatailDo) RightJoin(table schema.Tabler, on ...field.Expr) IImportProductsDatailDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i importProductsDatailDo) Group(cols ...field.Expr) IImportProductsDatailDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i importProductsDatailDo) Having(conds ...gen.Condition) IImportProductsDatailDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i importProductsDatailDo) Limit(limit int) IImportProductsDatailDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i importProductsDatailDo) Offset(offset int) IImportProductsDatailDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i importProductsDatailDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IImportProductsDatailDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i importProductsDatailDo) Unscoped() IImportProductsDatailDo {
	return i.withDO(i.DO.Unscoped())
}

func (i importProductsDatailDo) Create(values ...*models.ImportProductsDatail) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i importProductsDatailDo) CreateInBatches(values []*models.ImportProductsDatail, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i importProductsDatailDo) Save(values ...*models.ImportProductsDatail) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i importProductsDatailDo) First() (*models.ImportProductsDatail, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatail), nil
	}
}

func (i importProductsDatailDo) Take() (*models.ImportProductsDatail, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatail), nil
	}
}

func (i importProductsDatailDo) Last() (*models.ImportProductsDatail, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatail), nil
	}
}

func (i importProductsDatailDo) Find() ([]*models.ImportProductsDatail, error) {
	result, err := i.DO.Find()
	return result.([]*models.ImportProductsDatail), err
}

func (i importProductsDatailDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ImportProductsDatail, err error) {
	buf := make([]*models.ImportProductsDatail, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i importProductsDatailDo) FindInBatches(result *[]*models.ImportProductsDatail, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i importProductsDatailDo) Attrs(attrs ...field.AssignExpr) IImportProductsDatailDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i importProductsDatailDo) Assign(attrs ...field.AssignExpr) IImportProductsDatailDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i importProductsDatailDo) Joins(fields ...field.RelationField) IImportProductsDatailDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i importProductsDatailDo) Preload(fields ...field.RelationField) IImportProductsDatailDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i importProductsDatailDo) FirstOrInit() (*models.ImportProductsDatail, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatail), nil
	}
}

func (i importProductsDatailDo) FirstOrCreate() (*models.ImportProductsDatail, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ImportProductsDatail), nil
	}
}

func (i importProductsDatailDo) FindByPage(offset int, limit int) (result []*models.ImportProductsDatail, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i importProductsDatailDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i importProductsDatailDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i importProductsDatailDo) Delete(models ...*models.ImportProductsDatail) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *importProductsDatailDo) withDO(do gen.Dao) *importProductsDatailDo {
	i.DO = *do.(*gen.DO)
	return i
}
