// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-api/internal/pkg/models"
)

func newIncome(db *gorm.DB, opts ...gen.DOOption) income {
	_income := income{}

	_income.incomeDo.UseDB(db, opts...)
	_income.incomeDo.UseModel(&models.Income{})

	tableName := _income.incomeDo.TableName()
	_income.ALL = field.NewAsterisk(tableName)
	_income.ID = field.NewString(tableName, "id")
	_income.IncomeDate = field.NewTime(tableName, "income_date")
	_income.Amount = field.NewFloat64(tableName, "amount")
	_income.Description = field.NewString(tableName, "description")
	_income.SlipURL = field.NewString(tableName, "slip_url")
	_income.ProductID = field.NewString(tableName, "product_id")
	_income.CategoryID = field.NewString(tableName, "category_id")
	_income.CreatedAt = field.NewTime(tableName, "created_at")

	_income.fillFieldMap()

	return _income
}

type income struct {
	incomeDo

	ALL         field.Asterisk
	ID          field.String
	IncomeDate  field.Time
	Amount      field.Float64
	Description field.String
	SlipURL     field.String
	ProductID   field.String
	CategoryID  field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (i income) Table(newTableName string) *income {
	i.incomeDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i income) As(alias string) *income {
	i.incomeDo.DO = *(i.incomeDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *income) updateTableName(table string) *income {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.IncomeDate = field.NewTime(table, "income_date")
	i.Amount = field.NewFloat64(table, "amount")
	i.Description = field.NewString(table, "description")
	i.SlipURL = field.NewString(table, "slip_url")
	i.ProductID = field.NewString(table, "product_id")
	i.CategoryID = field.NewString(table, "category_id")
	i.CreatedAt = field.NewTime(table, "created_at")

	i.fillFieldMap()

	return i
}

func (i *income) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *income) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 8)
	i.fieldMap["id"] = i.ID
	i.fieldMap["income_date"] = i.IncomeDate
	i.fieldMap["amount"] = i.Amount
	i.fieldMap["description"] = i.Description
	i.fieldMap["slip_url"] = i.SlipURL
	i.fieldMap["product_id"] = i.ProductID
	i.fieldMap["category_id"] = i.CategoryID
	i.fieldMap["created_at"] = i.CreatedAt
}

func (i income) clone(db *gorm.DB) income {
	i.incomeDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i income) replaceDB(db *gorm.DB) income {
	i.incomeDo.ReplaceDB(db)
	return i
}

type incomeDo struct{ gen.DO }

type IIncomeDo interface {
	gen.SubQuery
	Debug() IIncomeDo
	WithContext(ctx context.Context) IIncomeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIncomeDo
	WriteDB() IIncomeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIncomeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIncomeDo
	Not(conds ...gen.Condition) IIncomeDo
	Or(conds ...gen.Condition) IIncomeDo
	Select(conds ...field.Expr) IIncomeDo
	Where(conds ...gen.Condition) IIncomeDo
	Order(conds ...field.Expr) IIncomeDo
	Distinct(cols ...field.Expr) IIncomeDo
	Omit(cols ...field.Expr) IIncomeDo
	Join(table schema.Tabler, on ...field.Expr) IIncomeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIncomeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIncomeDo
	Group(cols ...field.Expr) IIncomeDo
	Having(conds ...gen.Condition) IIncomeDo
	Limit(limit int) IIncomeDo
	Offset(offset int) IIncomeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIncomeDo
	Unscoped() IIncomeDo
	Create(values ...*models.Income) error
	CreateInBatches(values []*models.Income, batchSize int) error
	Save(values ...*models.Income) error
	First() (*models.Income, error)
	Take() (*models.Income, error)
	Last() (*models.Income, error)
	Find() ([]*models.Income, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Income, err error)
	FindInBatches(result *[]*models.Income, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Income) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIncomeDo
	Assign(attrs ...field.AssignExpr) IIncomeDo
	Joins(fields ...field.RelationField) IIncomeDo
	Preload(fields ...field.RelationField) IIncomeDo
	FirstOrInit() (*models.Income, error)
	FirstOrCreate() (*models.Income, error)
	FindByPage(offset int, limit int) (result []*models.Income, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIncomeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i incomeDo) Debug() IIncomeDo {
	return i.withDO(i.DO.Debug())
}

func (i incomeDo) WithContext(ctx context.Context) IIncomeDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i incomeDo) ReadDB() IIncomeDo {
	return i.Clauses(dbresolver.Read)
}

func (i incomeDo) WriteDB() IIncomeDo {
	return i.Clauses(dbresolver.Write)
}

func (i incomeDo) Session(config *gorm.Session) IIncomeDo {
	return i.withDO(i.DO.Session(config))
}

func (i incomeDo) Clauses(conds ...clause.Expression) IIncomeDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i incomeDo) Returning(value interface{}, columns ...string) IIncomeDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i incomeDo) Not(conds ...gen.Condition) IIncomeDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i incomeDo) Or(conds ...gen.Condition) IIncomeDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i incomeDo) Select(conds ...field.Expr) IIncomeDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i incomeDo) Where(conds ...gen.Condition) IIncomeDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i incomeDo) Order(conds ...field.Expr) IIncomeDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i incomeDo) Distinct(cols ...field.Expr) IIncomeDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i incomeDo) Omit(cols ...field.Expr) IIncomeDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i incomeDo) Join(table schema.Tabler, on ...field.Expr) IIncomeDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i incomeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIncomeDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i incomeDo) RightJoin(table schema.Tabler, on ...field.Expr) IIncomeDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i incomeDo) Group(cols ...field.Expr) IIncomeDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i incomeDo) Having(conds ...gen.Condition) IIncomeDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i incomeDo) Limit(limit int) IIncomeDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i incomeDo) Offset(offset int) IIncomeDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i incomeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIncomeDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i incomeDo) Unscoped() IIncomeDo {
	return i.withDO(i.DO.Unscoped())
}

func (i incomeDo) Create(values ...*models.Income) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i incomeDo) CreateInBatches(values []*models.Income, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i incomeDo) Save(values ...*models.Income) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i incomeDo) First() (*models.Income, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Income), nil
	}
}

func (i incomeDo) Take() (*models.Income, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Income), nil
	}
}

func (i incomeDo) Last() (*models.Income, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Income), nil
	}
}

func (i incomeDo) Find() ([]*models.Income, error) {
	result, err := i.DO.Find()
	return result.([]*models.Income), err
}

func (i incomeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Income, err error) {
	buf := make([]*models.Income, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i incomeDo) FindInBatches(result *[]*models.Income, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i incomeDo) Attrs(attrs ...field.AssignExpr) IIncomeDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i incomeDo) Assign(attrs ...field.AssignExpr) IIncomeDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i incomeDo) Joins(fields ...field.RelationField) IIncomeDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i incomeDo) Preload(fields ...field.RelationField) IIncomeDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i incomeDo) FirstOrInit() (*models.Income, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Income), nil
	}
}

func (i incomeDo) FirstOrCreate() (*models.Income, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Income), nil
	}
}

func (i incomeDo) FindByPage(offset int, limit int) (result []*models.Income, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i incomeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i incomeDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i incomeDo) Delete(models ...*models.Income) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *incomeDo) withDO(do gen.Dao) *incomeDo {
	i.DO = *do.(*gen.DO)
	return i
}
