// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-api/internal/pkg/models"
)

func newIncomeCategory(db *gorm.DB, opts ...gen.DOOption) incomeCategory {
	_incomeCategory := incomeCategory{}

	_incomeCategory.incomeCategoryDo.UseDB(db, opts...)
	_incomeCategory.incomeCategoryDo.UseModel(&models.IncomeCategory{})

	tableName := _incomeCategory.incomeCategoryDo.TableName()
	_incomeCategory.ALL = field.NewAsterisk(tableName)
	_incomeCategory.ID = field.NewString(tableName, "id")
	_incomeCategory.CategoryName = field.NewString(tableName, "category_name")
	_incomeCategory.Description = field.NewString(tableName, "description")

	_incomeCategory.fillFieldMap()

	return _incomeCategory
}

type incomeCategory struct {
	incomeCategoryDo

	ALL          field.Asterisk
	ID           field.String
	CategoryName field.String
	Description  field.String

	fieldMap map[string]field.Expr
}

func (i incomeCategory) Table(newTableName string) *incomeCategory {
	i.incomeCategoryDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i incomeCategory) As(alias string) *incomeCategory {
	i.incomeCategoryDo.DO = *(i.incomeCategoryDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *incomeCategory) updateTableName(table string) *incomeCategory {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.CategoryName = field.NewString(table, "category_name")
	i.Description = field.NewString(table, "description")

	i.fillFieldMap()

	return i
}

func (i *incomeCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *incomeCategory) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 3)
	i.fieldMap["id"] = i.ID
	i.fieldMap["category_name"] = i.CategoryName
	i.fieldMap["description"] = i.Description
}

func (i incomeCategory) clone(db *gorm.DB) incomeCategory {
	i.incomeCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i incomeCategory) replaceDB(db *gorm.DB) incomeCategory {
	i.incomeCategoryDo.ReplaceDB(db)
	return i
}

type incomeCategoryDo struct{ gen.DO }

type IIncomeCategoryDo interface {
	gen.SubQuery
	Debug() IIncomeCategoryDo
	WithContext(ctx context.Context) IIncomeCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIncomeCategoryDo
	WriteDB() IIncomeCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIncomeCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIncomeCategoryDo
	Not(conds ...gen.Condition) IIncomeCategoryDo
	Or(conds ...gen.Condition) IIncomeCategoryDo
	Select(conds ...field.Expr) IIncomeCategoryDo
	Where(conds ...gen.Condition) IIncomeCategoryDo
	Order(conds ...field.Expr) IIncomeCategoryDo
	Distinct(cols ...field.Expr) IIncomeCategoryDo
	Omit(cols ...field.Expr) IIncomeCategoryDo
	Join(table schema.Tabler, on ...field.Expr) IIncomeCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIncomeCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIncomeCategoryDo
	Group(cols ...field.Expr) IIncomeCategoryDo
	Having(conds ...gen.Condition) IIncomeCategoryDo
	Limit(limit int) IIncomeCategoryDo
	Offset(offset int) IIncomeCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIncomeCategoryDo
	Unscoped() IIncomeCategoryDo
	Create(values ...*models.IncomeCategory) error
	CreateInBatches(values []*models.IncomeCategory, batchSize int) error
	Save(values ...*models.IncomeCategory) error
	First() (*models.IncomeCategory, error)
	Take() (*models.IncomeCategory, error)
	Last() (*models.IncomeCategory, error)
	Find() ([]*models.IncomeCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.IncomeCategory, err error)
	FindInBatches(result *[]*models.IncomeCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.IncomeCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIncomeCategoryDo
	Assign(attrs ...field.AssignExpr) IIncomeCategoryDo
	Joins(fields ...field.RelationField) IIncomeCategoryDo
	Preload(fields ...field.RelationField) IIncomeCategoryDo
	FirstOrInit() (*models.IncomeCategory, error)
	FirstOrCreate() (*models.IncomeCategory, error)
	FindByPage(offset int, limit int) (result []*models.IncomeCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIncomeCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i incomeCategoryDo) Debug() IIncomeCategoryDo {
	return i.withDO(i.DO.Debug())
}

func (i incomeCategoryDo) WithContext(ctx context.Context) IIncomeCategoryDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i incomeCategoryDo) ReadDB() IIncomeCategoryDo {
	return i.Clauses(dbresolver.Read)
}

func (i incomeCategoryDo) WriteDB() IIncomeCategoryDo {
	return i.Clauses(dbresolver.Write)
}

func (i incomeCategoryDo) Session(config *gorm.Session) IIncomeCategoryDo {
	return i.withDO(i.DO.Session(config))
}

func (i incomeCategoryDo) Clauses(conds ...clause.Expression) IIncomeCategoryDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i incomeCategoryDo) Returning(value interface{}, columns ...string) IIncomeCategoryDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i incomeCategoryDo) Not(conds ...gen.Condition) IIncomeCategoryDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i incomeCategoryDo) Or(conds ...gen.Condition) IIncomeCategoryDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i incomeCategoryDo) Select(conds ...field.Expr) IIncomeCategoryDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i incomeCategoryDo) Where(conds ...gen.Condition) IIncomeCategoryDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i incomeCategoryDo) Order(conds ...field.Expr) IIncomeCategoryDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i incomeCategoryDo) Distinct(cols ...field.Expr) IIncomeCategoryDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i incomeCategoryDo) Omit(cols ...field.Expr) IIncomeCategoryDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i incomeCategoryDo) Join(table schema.Tabler, on ...field.Expr) IIncomeCategoryDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i incomeCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIncomeCategoryDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i incomeCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IIncomeCategoryDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i incomeCategoryDo) Group(cols ...field.Expr) IIncomeCategoryDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i incomeCategoryDo) Having(conds ...gen.Condition) IIncomeCategoryDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i incomeCategoryDo) Limit(limit int) IIncomeCategoryDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i incomeCategoryDo) Offset(offset int) IIncomeCategoryDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i incomeCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIncomeCategoryDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i incomeCategoryDo) Unscoped() IIncomeCategoryDo {
	return i.withDO(i.DO.Unscoped())
}

func (i incomeCategoryDo) Create(values ...*models.IncomeCategory) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i incomeCategoryDo) CreateInBatches(values []*models.IncomeCategory, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i incomeCategoryDo) Save(values ...*models.IncomeCategory) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i incomeCategoryDo) First() (*models.IncomeCategory, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.IncomeCategory), nil
	}
}

func (i incomeCategoryDo) Take() (*models.IncomeCategory, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.IncomeCategory), nil
	}
}

func (i incomeCategoryDo) Last() (*models.IncomeCategory, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.IncomeCategory), nil
	}
}

func (i incomeCategoryDo) Find() ([]*models.IncomeCategory, error) {
	result, err := i.DO.Find()
	return result.([]*models.IncomeCategory), err
}

func (i incomeCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.IncomeCategory, err error) {
	buf := make([]*models.IncomeCategory, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i incomeCategoryDo) FindInBatches(result *[]*models.IncomeCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i incomeCategoryDo) Attrs(attrs ...field.AssignExpr) IIncomeCategoryDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i incomeCategoryDo) Assign(attrs ...field.AssignExpr) IIncomeCategoryDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i incomeCategoryDo) Joins(fields ...field.RelationField) IIncomeCategoryDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i incomeCategoryDo) Preload(fields ...field.RelationField) IIncomeCategoryDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i incomeCategoryDo) FirstOrInit() (*models.IncomeCategory, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.IncomeCategory), nil
	}
}

func (i incomeCategoryDo) FirstOrCreate() (*models.IncomeCategory, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.IncomeCategory), nil
	}
}

func (i incomeCategoryDo) FindByPage(offset int, limit int) (result []*models.IncomeCategory, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i incomeCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i incomeCategoryDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i incomeCategoryDo) Delete(models ...*models.IncomeCategory) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *incomeCategoryDo) withDO(do gen.Dao) *incomeCategoryDo {
	i.DO = *do.(*gen.DO)
	return i
}
