// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-api/internal/pkg/models"
)

func newPage(db *gorm.DB, opts ...gen.DOOption) page {
	_page := page{}

	_page.pageDo.UseDB(db, opts...)
	_page.pageDo.UseModel(&models.Page{})

	tableName := _page.pageDo.TableName()
	_page.ALL = field.NewAsterisk(tableName)
	_page.ID = field.NewString(tableName, "id")
	_page.PageID = field.NewString(tableName, "page_id")
	_page.NamePage = field.NewString(tableName, "name_page")
	_page.Image = field.NewString(tableName, "image")

	_page.fillFieldMap()

	return _page
}

type page struct {
	pageDo

	ALL      field.Asterisk
	ID       field.String
	PageID   field.String
	NamePage field.String
	Image    field.String

	fieldMap map[string]field.Expr
}

func (p page) Table(newTableName string) *page {
	p.pageDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p page) As(alias string) *page {
	p.pageDo.DO = *(p.pageDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *page) updateTableName(table string) *page {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.PageID = field.NewString(table, "page_id")
	p.NamePage = field.NewString(table, "name_page")
	p.Image = field.NewString(table, "image")

	p.fillFieldMap()

	return p
}

func (p *page) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *page) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["id"] = p.ID
	p.fieldMap["page_id"] = p.PageID
	p.fieldMap["name_page"] = p.NamePage
	p.fieldMap["image"] = p.Image
}

func (p page) clone(db *gorm.DB) page {
	p.pageDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p page) replaceDB(db *gorm.DB) page {
	p.pageDo.ReplaceDB(db)
	return p
}

type pageDo struct{ gen.DO }

type IPageDo interface {
	gen.SubQuery
	Debug() IPageDo
	WithContext(ctx context.Context) IPageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPageDo
	WriteDB() IPageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPageDo
	Not(conds ...gen.Condition) IPageDo
	Or(conds ...gen.Condition) IPageDo
	Select(conds ...field.Expr) IPageDo
	Where(conds ...gen.Condition) IPageDo
	Order(conds ...field.Expr) IPageDo
	Distinct(cols ...field.Expr) IPageDo
	Omit(cols ...field.Expr) IPageDo
	Join(table schema.Tabler, on ...field.Expr) IPageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPageDo
	Group(cols ...field.Expr) IPageDo
	Having(conds ...gen.Condition) IPageDo
	Limit(limit int) IPageDo
	Offset(offset int) IPageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPageDo
	Unscoped() IPageDo
	Create(values ...*models.Page) error
	CreateInBatches(values []*models.Page, batchSize int) error
	Save(values ...*models.Page) error
	First() (*models.Page, error)
	Take() (*models.Page, error)
	Last() (*models.Page, error)
	Find() ([]*models.Page, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Page, err error)
	FindInBatches(result *[]*models.Page, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Page) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPageDo
	Assign(attrs ...field.AssignExpr) IPageDo
	Joins(fields ...field.RelationField) IPageDo
	Preload(fields ...field.RelationField) IPageDo
	FirstOrInit() (*models.Page, error)
	FirstOrCreate() (*models.Page, error)
	FindByPage(offset int, limit int) (result []*models.Page, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p pageDo) Debug() IPageDo {
	return p.withDO(p.DO.Debug())
}

func (p pageDo) WithContext(ctx context.Context) IPageDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pageDo) ReadDB() IPageDo {
	return p.Clauses(dbresolver.Read)
}

func (p pageDo) WriteDB() IPageDo {
	return p.Clauses(dbresolver.Write)
}

func (p pageDo) Session(config *gorm.Session) IPageDo {
	return p.withDO(p.DO.Session(config))
}

func (p pageDo) Clauses(conds ...clause.Expression) IPageDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pageDo) Returning(value interface{}, columns ...string) IPageDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pageDo) Not(conds ...gen.Condition) IPageDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pageDo) Or(conds ...gen.Condition) IPageDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pageDo) Select(conds ...field.Expr) IPageDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pageDo) Where(conds ...gen.Condition) IPageDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pageDo) Order(conds ...field.Expr) IPageDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pageDo) Distinct(cols ...field.Expr) IPageDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pageDo) Omit(cols ...field.Expr) IPageDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pageDo) Join(table schema.Tabler, on ...field.Expr) IPageDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPageDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pageDo) RightJoin(table schema.Tabler, on ...field.Expr) IPageDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pageDo) Group(cols ...field.Expr) IPageDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pageDo) Having(conds ...gen.Condition) IPageDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pageDo) Limit(limit int) IPageDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pageDo) Offset(offset int) IPageDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPageDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pageDo) Unscoped() IPageDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pageDo) Create(values ...*models.Page) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pageDo) CreateInBatches(values []*models.Page, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pageDo) Save(values ...*models.Page) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pageDo) First() (*models.Page, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Page), nil
	}
}

func (p pageDo) Take() (*models.Page, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Page), nil
	}
}

func (p pageDo) Last() (*models.Page, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Page), nil
	}
}

func (p pageDo) Find() ([]*models.Page, error) {
	result, err := p.DO.Find()
	return result.([]*models.Page), err
}

func (p pageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Page, err error) {
	buf := make([]*models.Page, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pageDo) FindInBatches(result *[]*models.Page, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pageDo) Attrs(attrs ...field.AssignExpr) IPageDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pageDo) Assign(attrs ...field.AssignExpr) IPageDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pageDo) Joins(fields ...field.RelationField) IPageDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pageDo) Preload(fields ...field.RelationField) IPageDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pageDo) FirstOrInit() (*models.Page, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Page), nil
	}
}

func (p pageDo) FirstOrCreate() (*models.Page, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Page), nil
	}
}

func (p pageDo) FindByPage(offset int, limit int) (result []*models.Page, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pageDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pageDo) Delete(models ...*models.Page) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pageDo) withDO(do gen.Dao) *pageDo {
	p.DO = *do.(*gen.DO)
	return p
}
