// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-api/internal/pkg/models"
)

func newProductsResearch(db *gorm.DB, opts ...gen.DOOption) productsResearch {
	_productsResearch := productsResearch{}

	_productsResearch.productsResearchDo.UseDB(db, opts...)
	_productsResearch.productsResearchDo.UseModel(&models.ProductsResearch{})

	tableName := _productsResearch.productsResearchDo.TableName()
	_productsResearch.ALL = field.NewAsterisk(tableName)
	_productsResearch.ID = field.NewFloat64(tableName, "id ")
	_productsResearch.Link = field.NewString(tableName, "link")
	_productsResearch.ProductsDetails = field.NewString(tableName, "products_details")
	_productsResearch.ProductsLaoDetails = field.NewString(tableName, "products_lao_details")

	_productsResearch.fillFieldMap()

	return _productsResearch
}

type productsResearch struct {
	productsResearchDo

	ALL                field.Asterisk
	ID                 field.Float64
	Link               field.String
	ProductsDetails    field.String
	ProductsLaoDetails field.String

	fieldMap map[string]field.Expr
}

func (p productsResearch) Table(newTableName string) *productsResearch {
	p.productsResearchDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productsResearch) As(alias string) *productsResearch {
	p.productsResearchDo.DO = *(p.productsResearchDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productsResearch) updateTableName(table string) *productsResearch {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewFloat64(table, "id ")
	p.Link = field.NewString(table, "link")
	p.ProductsDetails = field.NewString(table, "products_details")
	p.ProductsLaoDetails = field.NewString(table, "products_lao_details")

	p.fillFieldMap()

	return p
}

func (p *productsResearch) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productsResearch) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["id "] = p.ID
	p.fieldMap["link"] = p.Link
	p.fieldMap["products_details"] = p.ProductsDetails
	p.fieldMap["products_lao_details"] = p.ProductsLaoDetails
}

func (p productsResearch) clone(db *gorm.DB) productsResearch {
	p.productsResearchDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productsResearch) replaceDB(db *gorm.DB) productsResearch {
	p.productsResearchDo.ReplaceDB(db)
	return p
}

type productsResearchDo struct{ gen.DO }

type IProductsResearchDo interface {
	gen.SubQuery
	Debug() IProductsResearchDo
	WithContext(ctx context.Context) IProductsResearchDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductsResearchDo
	WriteDB() IProductsResearchDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductsResearchDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductsResearchDo
	Not(conds ...gen.Condition) IProductsResearchDo
	Or(conds ...gen.Condition) IProductsResearchDo
	Select(conds ...field.Expr) IProductsResearchDo
	Where(conds ...gen.Condition) IProductsResearchDo
	Order(conds ...field.Expr) IProductsResearchDo
	Distinct(cols ...field.Expr) IProductsResearchDo
	Omit(cols ...field.Expr) IProductsResearchDo
	Join(table schema.Tabler, on ...field.Expr) IProductsResearchDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductsResearchDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductsResearchDo
	Group(cols ...field.Expr) IProductsResearchDo
	Having(conds ...gen.Condition) IProductsResearchDo
	Limit(limit int) IProductsResearchDo
	Offset(offset int) IProductsResearchDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductsResearchDo
	Unscoped() IProductsResearchDo
	Create(values ...*models.ProductsResearch) error
	CreateInBatches(values []*models.ProductsResearch, batchSize int) error
	Save(values ...*models.ProductsResearch) error
	First() (*models.ProductsResearch, error)
	Take() (*models.ProductsResearch, error)
	Last() (*models.ProductsResearch, error)
	Find() ([]*models.ProductsResearch, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ProductsResearch, err error)
	FindInBatches(result *[]*models.ProductsResearch, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ProductsResearch) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductsResearchDo
	Assign(attrs ...field.AssignExpr) IProductsResearchDo
	Joins(fields ...field.RelationField) IProductsResearchDo
	Preload(fields ...field.RelationField) IProductsResearchDo
	FirstOrInit() (*models.ProductsResearch, error)
	FirstOrCreate() (*models.ProductsResearch, error)
	FindByPage(offset int, limit int) (result []*models.ProductsResearch, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductsResearchDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productsResearchDo) Debug() IProductsResearchDo {
	return p.withDO(p.DO.Debug())
}

func (p productsResearchDo) WithContext(ctx context.Context) IProductsResearchDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productsResearchDo) ReadDB() IProductsResearchDo {
	return p.Clauses(dbresolver.Read)
}

func (p productsResearchDo) WriteDB() IProductsResearchDo {
	return p.Clauses(dbresolver.Write)
}

func (p productsResearchDo) Session(config *gorm.Session) IProductsResearchDo {
	return p.withDO(p.DO.Session(config))
}

func (p productsResearchDo) Clauses(conds ...clause.Expression) IProductsResearchDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productsResearchDo) Returning(value interface{}, columns ...string) IProductsResearchDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productsResearchDo) Not(conds ...gen.Condition) IProductsResearchDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productsResearchDo) Or(conds ...gen.Condition) IProductsResearchDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productsResearchDo) Select(conds ...field.Expr) IProductsResearchDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productsResearchDo) Where(conds ...gen.Condition) IProductsResearchDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productsResearchDo) Order(conds ...field.Expr) IProductsResearchDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productsResearchDo) Distinct(cols ...field.Expr) IProductsResearchDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productsResearchDo) Omit(cols ...field.Expr) IProductsResearchDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productsResearchDo) Join(table schema.Tabler, on ...field.Expr) IProductsResearchDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productsResearchDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductsResearchDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productsResearchDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductsResearchDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productsResearchDo) Group(cols ...field.Expr) IProductsResearchDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productsResearchDo) Having(conds ...gen.Condition) IProductsResearchDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productsResearchDo) Limit(limit int) IProductsResearchDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productsResearchDo) Offset(offset int) IProductsResearchDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productsResearchDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductsResearchDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productsResearchDo) Unscoped() IProductsResearchDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productsResearchDo) Create(values ...*models.ProductsResearch) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productsResearchDo) CreateInBatches(values []*models.ProductsResearch, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productsResearchDo) Save(values ...*models.ProductsResearch) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productsResearchDo) First() (*models.ProductsResearch, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProductsResearch), nil
	}
}

func (p productsResearchDo) Take() (*models.ProductsResearch, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProductsResearch), nil
	}
}

func (p productsResearchDo) Last() (*models.ProductsResearch, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProductsResearch), nil
	}
}

func (p productsResearchDo) Find() ([]*models.ProductsResearch, error) {
	result, err := p.DO.Find()
	return result.([]*models.ProductsResearch), err
}

func (p productsResearchDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ProductsResearch, err error) {
	buf := make([]*models.ProductsResearch, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productsResearchDo) FindInBatches(result *[]*models.ProductsResearch, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productsResearchDo) Attrs(attrs ...field.AssignExpr) IProductsResearchDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productsResearchDo) Assign(attrs ...field.AssignExpr) IProductsResearchDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productsResearchDo) Joins(fields ...field.RelationField) IProductsResearchDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productsResearchDo) Preload(fields ...field.RelationField) IProductsResearchDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productsResearchDo) FirstOrInit() (*models.ProductsResearch, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProductsResearch), nil
	}
}

func (p productsResearchDo) FirstOrCreate() (*models.ProductsResearch, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProductsResearch), nil
	}
}

func (p productsResearchDo) FindByPage(offset int, limit int) (result []*models.ProductsResearch, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productsResearchDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productsResearchDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productsResearchDo) Delete(models ...*models.ProductsResearch) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productsResearchDo) withDO(do gen.Dao) *productsResearchDo {
	p.DO = *do.(*gen.DO)
	return p
}
